name: Janet CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout testament
      uses: actions/checkout@v2
    - name: find latest version of janet
      uses: oprypin/find-latest-tag@v1
      with:
        repository: janet-lang/janet
        releases_only: true
        prefix: 'v'
      id: janet-ver
    - name: download janet
      run: curl -LO https://github.com/janet-lang/janet/archive/${{ steps.janet-ver.outputs.tag }}.tar.gz
    - name: extract source
      run: tar -xvzf ${{ steps.janet-ver.outputs.tag }}.tar.gz
    - name: build janet
      run: cd ${{ steps.janet-ver.outputs.tag }} && make && make install
    - name: change back to testament
      run: cd ..
    - name: run tests
      run: /usr/bin/env jpm test
